version: '3'

networks:
  monitoring:
    driver: bridge
    
volumes:
  prometheus:
  grafana:

services:
  node-exporter:
    image: prom/node-exporter:v1.3.1
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100
    networks:
      - monitoring

  docker-exporter:
    image: docker-exporter
    restart: unless-stopped
    build: 
      context: ./docker-exporter
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    expose: 
      - 9100
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:v2.32.1
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    expose:
      - 9090
    ports:
      - 9090:9090
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:8.3.4
    user: "0"
    restart: always
    volumes:
      - grafana:/var/lib/grafana
    ports:
      - 3000:3000
    networks:
      - monitoring